### ISSUE TITLE
Respect Task section header when moving tasks to today

### ISSUE THREAD

**Issue by finn-matti** [tgrosinger/slated-obsidian#60]
**Is your feature request related to a problem? Please describe.**
Right now, when moving incomplete tasks to today, they simply get appended to the end of the file.

**Describe the solution you'd like**
When moving tasks, make it so that moved tasks aren't simply appended to the end of the file, but rather look for the task section header and put the tasks there.

**Describe alternatives you've considered**
Moving them by hand, but that seems impractical.

**Additional context**
- Obsidian 0.11.0
- Slated 0.2.1

**Comment by tgrosinger** [comment]
Hmm, this should exist. Do you have the tasks section header set in the Slated settings?

Can you provide me an example of note contents that you move tasks from, as well as the note contents you move it to?

**Comment by finn-matti** [comment]
Here is a screencast of what's going on:

![2021-02-28-obsidian-slated-moving-tasks](https://user-images.githubusercontent.com/56148301/109412740-6de81d00-79b2-11eb-9644-d9cdbf177336.gif)

You can see that it somehow even moves the Day Planner section around, which it shouldn't either, right?

**Comment by finn-matti** [comment]
I guess that the footer section of my daily note template, which is not separated by anything from the backlog section, is interpreted as the body of the baglog and tasks are simply appended to that body. This makes sense. Moving around the day planner section however still seems weird to me.

**Comment by tgrosinger** [comment]
You are correct, that any non-header text after a header is interpreted as part of that section. New tasks will be added to the end of that section.

The Day Planner section is created at the end of the file because it did not already exist. If it had existed elsewhere in the file the tasks would have been placed under the heading at that location. I do not think I can easily determine where to put a heading in a new file since the file contents could be vastly different. Appending it to the end of the file is the most reliable solution.
