### ISSUE TITLE
Copy not delete moved tasks

### ISSUE THREAD

**Issue by ab-ll** [tgrosinger/slated-obsidian#68]
I loved the reference to the creating tasks that you removed for complexity reason.  I like knowing what I had on my plate on a day not having them removed, even if I did not get to them. Is it possible that you could add an option that does not delete them when moving them, just copies them? I have not looked at the code but it is possible to run a move all incomplete tasks to current day and then ctrl z to undo the deletes which seems to happen at the end of the process, so if you could have a flag that just ignores that part of the routine it would be great.  Thanks

**Comment by tgrosinger** [comment]
Hmm, I could imagine having a setting to mark tasks as complete and then copy them to a new note. Is that about what you're thinking? Alternatively we could go back to using `[>]` when moved. I just don't want to link between the tasks.

**Comment by cotemaxime** [comment]
I would like that option too, the [>] when moved as a settings, I have some cases where it would be really helpful, like moving project's tasks into the daily note, but keeping track of that task so I can easily keep track of tasks that have already been planned or not.

**Comment by ab-ll** [comment]
If possible having the > and leaving them in place as an option would work well for me.

**Comment by Araly** [comment]
I really like the "bullet journal" behavior Slated had with keeping in the daily note what happened, and not removing information. The links were niceties but not essential, as it's kind of implied that the tasks moved to the next daily note. I think a lot of us would be very happy with a behavior where:

- you have incomplete tasks for a daily note.
- you run the "Slated: Move all incomplete tasks to today"
- all the incomplete tasks get a `- [>]` to signify that they have been moved
- all the incomplete tasks can be found in the today daily note with an empty box `- [ ]`

With this behavior, it's very close to the way the bullet journal works https://bulletjournal.com/pages/learn which is what seems to be what a lot of people use

**Comment by tgrosinger** [comment]
Glad to hear the support. I'll work on this soon.

**Comment by JenFau** [comment]
Hi, thanks for your great plug in - it's one of my most used. 

I have to say, I really loved having the links. I use this plugin on a vault dedicated to work notes - I can use a separate note per meeting to capture notes and actions, run 'move to today' on the actions, and I can see in the daily view exactly which meeting those actions came from. I've actually built an entire workflow around this and I'll have to think very hard about how to handle actions if I can't see their source. 

The functionality that Araly outlined above would be welcome (in fact, essential for my current usage) but having the links back would be amazing.

**Comment by tgrosinger** [comment]
One possible solution to the links would be using the [review plugin](https://github.com/ryanjamurphy/review-obsidian).

**Comment by JenFau** [comment]
> One possible solution to the links would be using the [review plugin](https://github.com/ryanjamurphy/review-obsidian).

That would just create a link to the sheet rather than the tasks, I think? I'm not sure that would fit my workflow. 

My workflow at the moment is: 
- Create a new note for meeting ('planning meeting 20210421)
- Jot down actions as they arise (- [ ] Send plan to team)
- Using slate, move non immediate actions to a dedicate master 'to do' note for future review. 
- Using slate, move all non completed actions to today's daily note. 

The two **invaluable** resulting views are: 
- A record in the meeting note of what action were taken in that meeting with the > sign to show they've been moved. When next attending a meeting of that nature, I can refer back to the actions taken in that previous meeting. This avoids having to take a note as an enduring record of what was discussed _and_ an accompanying action on the same topic when an action can do the job of both. e.g. '- [ ] send discussed plan to team' that remains as a > action after moving is much better than a note 'discussed plan with team - to be circulated' and _then_ a '- [ ] send plan to team'
- List of open actions in either master 'to do' note or daily note with link back to source. When reviewing my current to do list, either for my own purposes or with my manager, I can immediately see and jump to the meeting notes from where that action arose. This is so invaluable for getting the context and means I don't have to include a ton of stuff in the action for it to make complete sense on its own.

**Comment by zolrath** [comment]
Having the option of copying the task into the next note and transforming the deferred task into [>] would be great for me to be able to more easily understand how many times a task has been pushed to another date.
Especially when combined with @death_au's checkbox css
https://discord.com/channels/686053708261228577/702656734631821413/836099935874056193

**Comment by samxsmith** [comment]
Have opened a PR to implement this feature
https://github.com/tgrosinger/slated-obsidian/pull/74

**Comment by tgrosinger** [comment]
Merged and releasing in 0.5.0.
